version: 0.2

phases:
  install:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - ls
  pre_build:
    commands:
      - pwd
      - terraform init
      - terraform validate
  build:
    commands:
        - terraform destroy -auto-approve
  post_build:
    commands:
       - echo "Terraform encironment Destroyed" 
